var classMoreSlugcats_1_1MoreSlugcatsEnums =
[
    [ "AbstractObjectType", "d8/dd2/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1AbstractObjectType.html", null ],
    [ "ConversationID", "df/d68/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1ConversationID.html", null ],
    [ "CreatureTemplateType", "df/dd7/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1CreatureTemplateType.html", null ],
    [ "DamageType", "d4/d1e/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1DamageType.html", null ],
    [ "DataPearlType", "dd/dad/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1DataPearlType.html", null ],
    [ "DeathRainMode", "d3/dcb/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1DeathRainMode.html", null ],
    [ "DreamID", "d5/d35/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1DreamID.html", null ],
    [ "EggBugBehavior", "da/d82/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1EggBugBehavior.html", null ],
    [ "EndgameID", "d3/d95/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1EndgameID.html", null ],
    [ "GameTypeID", "da/dec/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1GameTypeID.html", null ],
    [ "GateRequirement", "de/d5a/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1GateRequirement.html", null ],
    [ "GhostID", "d3/dff/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1GhostID.html", null ],
    [ "LevelUnlockID", "da/d88/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1LevelUnlockID.html", null ],
    [ "MainWormBehaviorPhase", "d2/d65/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1MainWormBehaviorPhase.html", null ],
    [ "MenuSceneID", "db/de2/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1MenuSceneID.html", null ],
    [ "MiscItemType", "df/d20/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1MiscItemType.html", null ],
    [ "MSCSoundID", "d3/d5b/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1MSCSoundID.html", null ],
    [ "OracleID", "dc/d9c/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1OracleID.html", null ],
    [ "OverseerHologramMessage", "d7/d01/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1OverseerHologramMessage.html", null ],
    [ "OwnerType", "d7/dc8/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1OwnerType.html", null ],
    [ "PlacedObjectType", "db/d37/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1PlacedObjectType.html", null ],
    [ "ProcessID", "dd/d3f/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1ProcessID.html", null ],
    [ "RoomEffectType", "d4/dc6/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1RoomEffectType.html", null ],
    [ "RoomRainDangerType", "d0/d10/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1RoomRainDangerType.html", null ],
    [ "SandboxUnlockID", "d7/d7d/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1SandboxUnlockID.html", null ],
    [ "ScavengerAnimationID", "d1/dfb/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1ScavengerAnimationID.html", null ],
    [ "SlideShowID", "d9/dbd/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1SlideShowID.html", null ],
    [ "SlugcatStatsName", "d0/d0f/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1SlugcatStatsName.html", null ],
    [ "SSOracleBehaviorAction", "db/dba/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1SSOracleBehaviorAction.html", null ],
    [ "SSOracleBehaviorSubBehavID", "d5/d58/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1SSOracleBehaviorSubBehavID.html", null ],
    [ "TickerID", "d2/db6/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1TickerID.html", null ],
    [ "Tutorial", "de/d6d/classMoreSlugcats_1_1MoreSlugcatsEnums_1_1Tutorial.html", null ]
];